services:
  db:
    image: postgres:18-alpine
    container_name: nba_h2h_postgresql_production
    restart: unless-stopped
    env_file: .env.production
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - nba_postgres_data_production:/var/lib/postgresql
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DATABASE"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    image: pedroadiniz/nba-statics-api-postgresql:latest
    container_name: nba_h2h_api_postgresql_production
    restart: unless-stopped
    env_file: .env.production
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db_net
      - public_net

networks:
  db_net:
    internal: true
  public_net:

volumes:
  nba_postgres_data_production:
    name: nba_postgres_data_production
