services:
  db:
    image: mysql:latest
    container_name: nba_h2h_mysql_development
    restart: unless-stopped
    env_file: .env.development
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - nba_mysql_data_development:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      args:
        DATABASE_ENGINE: mysql
    container_name: nba_h2h_api_mysql_development
    restart: unless-stopped
    env_file: .env.development
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy

volumes:
  nba_mysql_data_development:
    name: nba_mysql_data_development
