services:
  db:
    image: mysql:latest
    container_name: nba_h2h_mysql_production
    restart: unless-stopped
    env_file: .env.production
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - nba_mysql_data_production:/var/lib/mysql
    networks:
      - db_network_production
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $MYSQL_USER -p $MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    image: pedroadiniz/nba-statics-api-mysql:latest
    container_name: nba_h2h_api_mysql_production
    restart: unless-stopped
    env_file: .env.production
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db_network_production
      - public_network

networks:
  db_network_production:
    internal: true
  public_network:

volumes:
  nba_mysql_data_production:
    name: nba_mysql_data_production
